vich_uploader:
    db_driver: orm

    mappings:
        company_logo:
            uri_prefix: /img/company_logo
            upload_destination: '%kernel.project_dir%/public/img/company_logo'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update:   true
            delete_on_remove:   true

